triangles:
	g++ -O0 -g -lGLEW -lGL -lglut -I../include/ ../lib/LoadShaders.cpp triangles.cpp -o ../bin/triangles

simple:
	g++ -O0 -g -lGLEW -lGL -lglut -I../include simple.cpp ../lib/GLSLShader.cpp -o ../bin/simple

simple_triangle:
	g++ -O0 -g -lGLEW -lGL -lglut -I../include simple_triangle.cpp ../lib/GLSLShader.cpp -o ../bin/simple_triangle
